# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  base = ""
  publish = "packages/app/build/app"

  command = "echo BUILDING... && cd packages/plugin && yarn build && cd ../app && yarn build --standalone"

  ignore = "exit 0"